version: '3.8'

services:
  web:
    build: .
    command: gunicorn placesremember.wsgi:application -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: secrey
      POSTGRES_PASSWORD: speacsrsewyord
      POSTGRES_DB: placesrememberdc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
