# Generated by Django 5.0.6 on 2024-05-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
